runtime: python37
  
handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

env_variables:
    DEBUG: 'false'
    INSTANCE_CONNECTION_NAME: 'tfa-project-2021:us-west2:squirrel'  # eg. 'ieor-tools-for-analytics:asia-east1:adopt'
    PGDATABASE: 'postgres'
    PGUSER: 'postgres'
    PGPASSWORD: 'e0knBH4vuImoHdrj'
    SECRET_KEY: 'django-insecure-kn3sh$cizl+mc+_9_2z%^(b3kd(9luak!b+m4302$o%jbtl&bm'
    GS_BUCKET_NAME: 'tfa-project-2021.appspot.com'  # eg. 'ieor-tools-for-analytics.appspot.com'
    GOOGLE_APPLICATION_CREDENTIALS: 'service-account-key.json'  # eg. 'service-account-key.json'
