# Generated by Django 3.2 on 2021-04-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrels',
            fields=[
                ('X', models.DecimalField(decimal_places=20, help_text='Longtitude', max_digits=100)),
                ('Y', models.DecimalField(decimal_places=20, help_text='Latitude', max_digits=100)),
                ('Unique_squirrel_id', models.CharField(help_text='Unique Squiirel ID', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Shift', models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], help_text='Shift', max_length=15)),
                ('Date', models.DateField(help_text='Date: MMDDYYYY')),
                ('Age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('Other', 'Other')], help_text='Age', max_length=15, null=True)),
                ('Fur', models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black'), ('Other', 'Other')], help_text='Primary Fur Color', max_length=15, null=True)),
                ('Location', models.CharField(choices=[('Ground_Plane', 'Ground Plane'), ('Above_Ground', 'Above_Ground'), ('Other', 'Other')], max_length=15, null=True)),
                ('Specific_location', models.CharField(max_length=100, null=True)),
                ('Running', models.BooleanField(default=False, help_text='Running or not?')),
                ('Chasing', models.BooleanField(default=False, help_text='Chasing or not?')),
                ('Climbing', models.BooleanField(default=False, help_text='Climbing or not?')),
                ('Eating', models.BooleanField(default=False, help_text='Eating or not?')),
                ('Foraging', models.BooleanField(default=False, help_text='Foraging or not?')),
                ('Other_Activities', models.CharField(help_text='Other Activities', max_length=100, null=True)),
                ('Kuks', models.BooleanField(default=False, help_text='Kuks or not?')),
                ('Quaas', models.BooleanField(default=False, help_text='Quaas or not?')),
                ('Moans', models.BooleanField(default=False, help_text='Moans or not?')),
                ('Tail_Flags', models.BooleanField(default=False, help_text='Tail flags or nots?')),
                ('Tail_Twitches', models.BooleanField(default=False, help_text='Tail Twitches or nots?')),
                ('Approaches', models.BooleanField(default=False, help_text='Approaches or not?')),
                ('Indifferent', models.BooleanField(default=False, help_text='Indifferent or not?')),
                ('Runs_From', models.BooleanField(default=False, help_text='Runs From?')),
            ],
        ),
    ]
